language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"
  - "nightly"
install:
  - pip install -r requirements_dev.txt
  - pip install coveralls
script:
  - pytest --cov=notix tests/
after_success:
  - coveralls

deploy:
  provider: pypi
  username: "__token__"
  password: $TOKEN
  on:
    branch: main