site_name: notix-python
site_url: https://shreyanshu7101904.github.io/notix-python/
theme: 
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.tracking
  plugins:
    - search:
      lang: en
markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - meta
nav:
  - Notix Python: index.md
  - 'Api Reference':
        - 'get_url': notix/get_url.md
        - 'Notix class': notix/notix_api.md
        - 'ResponseParser class': notix/response_parser.md
  - Constants: constants/constant.md
  - Exceptions: exceptions/exceptions.md
extra:
  generator: false