site_name: My Docs
site_url: https://example.com/
theme: readthedocs
nav:
  - Notix Python: index.md
  - Notix Api:
      - get_url: notix/notix.md
      - Notix: notix/notix.md
      - ResponseParser: notix/notix.md
  - Exceptions: exceptions/exceptions.md
  - Constants: constants/constant.md
