site_name: notix-python
site_url: https://notix-python.readthedocs.io
theme: readthedocs
markdown_extensions:
  - markdown.extensions.admonition
  - meta
nav:
  - Notix Python: index.md
  - 'Api Reference':
        - 'get_url': notix/get_url.md
        - 'Notix class': notix/notix_api.md
        - 'ResponseParser class': notix/response_parser.md
  - Constants: constants/constant.md
  - Exceptions: exceptions/exceptions.md